apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: default
data:
  config.yaml: |
    tunnel: 7e7bb69b-e978-4db4-b63f-cd24586aa09d
    credentials-file: /etc/cloudflared/credentials.json
    transport-loglevel: warn
    ingress:
      - hostname: forgejo.kudofools.dev
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: woodpecker.kudofools.dev
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: openbao.kudofools.dev
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: intikepri.kudofools.dev
        service: http://traefik.kube-system.svc.cluster.local:80
      - service: http_status:404
