apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      default-kudofools-infra-rate-limit@kubernetescrd,
      default-kudofools-infra-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: forgejo.kudofools.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forgejo-service
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: woodpecker-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      default-kudofools-infra-rate-limit@kubernetescrd,
      default-kudofools-infra-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: woodpecker.kudofools.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: woodpecker
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbao-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      default-kudofools-infra-rate-limit@kubernetescrd,
      default-kudofools-infra-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: openbao.kudofools.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openbao
                port:
                  number: 8200
