apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - matrix-alertmanager-receiver.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - victoria-metrics.yaml
  - vmalertmanager.yaml
  - victoria-logs.yaml
  - vlagent.yaml
