apiVersion: v1
kind: Service
metadata:
  name: registry-nodeport
  namespace: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30050
