apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-secrets
  namespace: woodpecker
  labels:
    app.kubernetes.io/name: woodpecker
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: woodpecker-secrets
    deletionPolicy: Retain
  data:
    - secretKey: WOODPECKER_AGENT_SECRET
      remoteRef:
        key: kv/woodpecker/secrets
        property: WOODPECKER_AGENT_SECRET
    - secretKey: WOODPECKER_FORGEJO_CLIENT
      remoteRef:
        key: kv/woodpecker/secrets
        property: WOODPECKER_FORGEJO_CLIENT
    - secretKey: WOODPECKER_FORGEJO_SECRET
      remoteRef:
        key: kv/woodpecker/secrets
        property: WOODPECKER_FORGEJO_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-auth
  namespace: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: registry-auth
    deletionPolicy: Retain
  data:
    - secretKey: auth.htpasswd
      remoteRef:
        key: kv/registry/auth
        property: auth.htpasswd
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secrets
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: forgejo-secrets
    deletionPolicy: Retain
  data:
    - secretKey: LFS_JWT_SECRET
      remoteRef:
        key: kv/forgejo/secrets
        property: LFS_JWT_SECRET
    - secretKey: INTERNAL_TOKEN
      remoteRef:
        key: kv/forgejo/secrets
        property: INTERNAL_TOKEN
    - secretKey: JWT_SECRET
      remoteRef:
        key: kv/forgejo/secrets
        property: JWT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kudofools-infra-webhook
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: kudofools-infra-webhook
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: kv/kudofools-infra/webhook-token
        property: token
