apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    deletionPolicy: Retain
  data:
    - secretKey: admin-user
      remoteRef:
        key: kv/grafana/secrets
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: kv/grafana/secrets
        property: admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mar-secrets
  namespace: monitoring
  labels:
    app.kubernetes.io/name: matrix-alertmanager-receiver
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mar-secrets
    deletionPolicy: Retain
  data:
    - secretKey: MATRIX_ACCESS_TOKEN
      remoteRef:
        key: kv/matrix-alertmanager-receiver/secrets
        property: MATRIX_ACCESS_TOKEN
