apiVersion: v1
kind: Namespace
metadata:
  name: rathole
  labels:
    app.kubernetes.io/name: rathole
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
    tier: platform
