apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: intikepri-cms
  namespace: flux-system
spec:
  image: docker.io/izayoilv/intikepri-cms
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: intikepri-cms
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: intikepri-cms
  filterTags:
    pattern: '^build-(?P<number>\d{6})-sha-[a-f0-9]{8}$'
    extract: "$number"
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: intikepri-cms
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: intikepri-cms
  git:
    commit:
      author:
        email: fluxcd@users.noreply.github.com
        name: fluxcd
      messageTemplate: "chore(intikepri-cms): update image tag to {{ (index .Changed.Changes 0).NewValue }} [skip ci]"
    push:
      branch: main
  update:
    path: ./deploy
    strategy: Setters
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: intikepri-cms-image
  namespace: flux-system
spec:
  type: dockerhub
  secretRef:
    name: intikepri-cms-webhook
  resources:
    - kind: ImageRepository
      name: intikepri-cms
