apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: intikepri-static
  namespace: flux-system
spec:
  image: registry.kudofools.dev/intikepri/intikepri-static
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: intikepri-static
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: intikepri-static
  filterTags:
    pattern: '^build-(?P<number>\d{6})-sha-[a-f0-9]{8}$'
    extract: "$number"
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: intikepri-static
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: intikepri-static
  git:
    commit:
      author:
        email: fluxcd@users.noreply.github.com
        name: fluxcd
      messageTemplate: "chore(intikepri-static): update image tag to {{ (index .Changed.Changes 0).NewValue }} [skip ci]"
    push:
      branch: main
  update:
    path: ./deploy
    strategy: Setters
