apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mgb-temple-cms
  namespace: flux-system
spec:
  interval: 12h
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://forgejo.kudofools.dev/izayoilv/mgb-temple-cms.git
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: mgb-temple-cms-git
  namespace: flux-system
spec:
  type: github
  secretRef:
    name: mgb-temple-cms-webhook
  resources:
    - kind: GitRepository
      name: mgb-temple-cms
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mgb-temple-cms
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: mgb-temple-cms
  path: ./deploy
  prune: true
