apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data-pvc
  namespace: lldap
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
