apiVersion: netbird.io/v1alpha1
kind: NetworkRouter
metadata:
  name: kudofools-cluster
  namespace: netbird
  labels:
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  dnsZoneRef:
    name: kudofools.dev
  workloadOverride:
    replicas: 1
    podTemplate:
      spec:
        containers:
          - name: netbird
            resources:
              requests:
                cpu: 25m
                memory: 32Mi
              limits:
                cpu: 500m
                memory: 128Mi
          - name: kube-egress-forwarder
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                cpu: 200m
                memory: 64Mi
