apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zmk-west-cache
  namespace: woodpecker-pipelines
  labels:
    app.kubernetes.io/name: woodpecker
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
