apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
  namespace: zot
  labels:
    app.kubernetes.io/name: zot
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
data:
  config.json: |
    {
      "distSpecVersion": "1.1.1",
      "storage": {
        "rootDirectory": "/var/lib/zot",
        "dedupe": true,
        "gc": true
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "realm": "zot",
        "auth": {
          "ldap": {
            "credentialsFile": "/etc/zot/ldap-creds.json",
            "address": "lldap-ldap.lldap.svc",
            "port": 3890,
            "insecure": true,
            "baseDN": "dc=kudofools,dc=dev",
            "userAttribute": "uid",
            "userGroupAttribute": "memberOf",
            "subtreeSearch": true
          },
          "failDelay": 5
        },
        "accessControl": {
          "repositories": {
            "public/*": {
              "anonymousPolicy": ["read"],
              "defaultPolicy": ["read", "create", "update"]
            },
            "**": {
              "defaultPolicy": []
            }
          },
          "adminPolicy": {
            "users": ["admin"],
            "actions": ["read", "create", "update", "delete"]
          }
        }
      },
      "log": {
        "level": "info"
      }
    }
