apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - service-nodeport.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: zot-config
    files:
      - config.json
