apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-reflector-controller
  namespace: flux-system
  labels:
    app.kubernetes.io/component: image-reflector-controller
    app.kubernetes.io/part-of: flux
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-automation-controller
  namespace: flux-system
  labels:
    app.kubernetes.io/component: image-automation-controller
    app.kubernetes.io/part-of: flux
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-reflector-controller
  labels:
    app.kubernetes.io/component: image-reflector-controller
    app.kubernetes.io/part-of: flux
rules:
  - apiGroups: ["image.toolkit.fluxcd.io"]
    resources: ["imagepolicies", "imagerepositories"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["image.toolkit.fluxcd.io"]
    resources: ["imagepolicies/status", "imagerepositories/status"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-reflector-controller
  labels:
    app.kubernetes.io/component: image-reflector-controller
    app.kubernetes.io/part-of: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-reflector-controller
subjects:
  - kind: ServiceAccount
    name: image-reflector-controller
    namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-automation-controller
  labels:
    app.kubernetes.io/component: image-automation-controller
    app.kubernetes.io/part-of: flux
rules:
  - apiGroups: ["image.toolkit.fluxcd.io"]
    resources: ["imageupdateautomations"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["image.toolkit.fluxcd.io"]
    resources: ["imageupdateautomations/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories/status"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-automation-controller
  labels:
    app.kubernetes.io/component: image-automation-controller
    app.kubernetes.io/part-of: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-automation-controller
subjects:
  - kind: ServiceAccount
    name: image-automation-controller
    namespace: flux-system
