apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: netbird
  chartRef:
    kind: OCIRepository
    name: netbird-operator
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    managementURL: https://netbird.kudofools.dev
