apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - system/
  - platform/ingress/
  - platform/eso/
  - platform/tofu-controller/
  - platform/image-automation/
  - platform/cloudflared/
  - apps/openbao/
  - apps/lldap/
  - apps/forgejo/
  - apps/registry/
  - apps/zot/
  - apps/rathole/
  - apps/woodpecker/
