apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - system/
  - platform/ingress/
  - platform/eso/
  - platform/tofu-controller/
  - apps/openbao/
  - apps/forgejo/
  - apps/registry/
  - apps/woodpecker/
  - apps/cloudflared/
